"use client";
import Image from "next/image";
import { useEffect, useRef } from "react";

export const HomePageContent = () => {
  // refrences
  const images = useRef<HTMLImageElement[]>([]);
  const content = useRef<HTMLDivElement[]>([]);

  return (
    <div className=" w-screen flex flex-col  items-center ">
      {/* intro */}
      <div className="max-mobile:mt-[50px]  flex flex-col mobile:flex-row mobile:w-screen mobile:h-[700px]  justify-center items-center mobile:gap-[50px] bg-[#eef1f2]">
        <div>
          <Image
            src={
              "https://sparkle-world-studio-production.s3.ap-south-1.amazonaws.com/pexels-tyler-hendy-52062.jpg"
            }
            alt="img"
            width={400}
            height={400}
            className="w-[350px] mobile:w-[440px] h-[400px] mobile:h-[400px] "
          />
        </div>
        {/* content */}
        <div className=" relative w-[350px] mobile:w-[40vw] mobile:h-[500px] mobile:flex flex-col justify-center items-center ">
          {/* square box */}
          <div className="hidden mobile:block w-[300px] h-[500px] absolute  right-0 border-[20px] border-[#dfdfdf]  "></div>

          <h3 className="mt-[20px] font-[700] text-[23px] mobile:text-[35px] z-[3] ">
            Most Innovative Construction Startup of India
          </h3>
          <p className="z-[3]">
            From last 6 years, SPARKLE WORLD STUDIO has been constructing some
            of the best and unique designs in various cities, with our
            experience; we have found the team to meet the owner's desire and
            expectations. We believe in technology and enhanced the Virtual
            Reality and Augmented Reality to the Construction and Architecture
            Industry. Our experienced team of Designers and Engineers are
            dedicatedly and proactively measures the requirements of the clients
            and brings down on the papers than reality.
            <br />
            <br />
            We innovate through collaboration with our clients and team members.
            We add value to every project by offering thoughtful and creative
            design solutions that are generated by listening carefully and
            working together. Our designers have a passion for creating
            impactful spaces. Our designs leave lasting impressions by bringing
            to life our clients’ personality, brand and vision. We build
            longstanding relationships with our clients that reflect our
            commitment to outstanding service and design.
          </p>
        </div>
      </div>

      {/* construction managment */}
      <div className="mt-[50px] mobile:mt-[100px] flex flex-col  mobile:w-screen justify-center items-center mobile:gap-[50px]">
        <div className="relative mobile:w-[800px] mobile:h-[500px] mobile:flex flex-col justify-center items-center">
          {/* square box */}
          <div className="hidden mobile:block absolute w-[570px] h-[350px] right-0 bottom-0 border-[20px] border-[#dfdfdf] "></div>
          <Image
            src={
              "https://sparkle-world-studio-production.s3.ap-south-1.amazonaws.com/management.jpg"
            }
            alt="img"
            width={350}
            height={400}
            className=" w-[350px] mobile:w-[800px] h-[400px] z-[2] mobile:translate-x-[-10%] mobile:translate-y-[-10%]"
          />
        </div>
        {/* content */}
        <div className="w-[350px] mobile:w-[40vw]">
          <h3 className="mt-[20px] font-[700] text-[23px] mobile:text-[35px]">
            Construction Management
          </h3>
          <p className="">
            As in the world of project management we offer you wide- ranging
            experience in all aspects of construction, as a result, we can help
            you in reducing technical risks preventing construction errors,
            controlling budgets and effectively keeping your construction
            projects with planned schedules also to meet all the applicable
            requirements, clients based.
          </p>
        </div>
      </div>
      {/* services/ what we do */}
      <div>
        <div className="mt-[20px] ">
          <div className="w-[250px] mobile:w-[400px] h-[50px]  flex justify-evenly items-center cursor-pointer digonals-lines">
            <span className="w-[50px] group-hover:w-[60px] mobile:w-[70px] mobile:group-hover:w-[80px] h-[4px] bg-black "></span>
            <h3 className=" font-[700] text-[20px] mobile:text-[35px] capitalize">
              what we do
            </h3>
            <span className="w-[50px] group-hover:w-[60px] mobile:w-[70px] mobile:group-hover:w-[80px] h-[4px] bg-black "></span>
          </div>
        </div>
      </div>
      {/*our expert*/}
    </div>
  );
};
