import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Navigation, Provider, Loader } from "@/components";
import { Toaster } from "react-hot-toast";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";

const inter = Inter({ subsets: ["latin"] });

// opting out of caching
export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin=""
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Dela+Gothic+One&family=Martian+Mono:wght@800&display=swap"
          rel="stylesheet"
        />
        <title>Sparkle world studio</title>
      </head>
      <Provider>
        <body className={inter.className}>
          <header>
            <Navigation />
          </header>
          <main>
            <Loader />
            {children}
          </main>
          <Toaster position="top-right" reverseOrder={false} />
          <ReactQueryDevtools />
        </body>
      </Provider>
    </html>
  );
}
